#!/bin/bash

# INSTALLER FOR DEV MODE (NON-CONTAINERISED)

boldgreen="\033[1;32m"
endcolor="\033[0m"

echo -e "${boldgreen}Installing H2O...$endcolor"

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  yes | apt-get update
  yes | apt-get upgrade
  yes | apt install build-essential python3-dev python3-pip nodejs npm
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  apt-get update && apt-get install yarn
  pip3 install wheel

elif [[ "$OSTYPE" == "darwin"* ]]; then
  yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew update && brew upgrade
  brew install python node@8 yarn

fi

npm install -g @angular/cli

pip3 install --upgrade setuptools
pip3 install wheel

cd backend
pip3 install -r requirements.txt
npm install orbit-db ipfs # MOVE IF MIGRATING ORBIT TO FRONT END
cd ../frontend
yarn install --pure-lockfile

echo -e "$boldgreen
H2O installed.
$endcolor"
