#!/bin/bash

# INSTALLER FOR DEV MODE (NON-CONTAINERISED)

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  yes | apt-get update
  yes | apt-get upgrade
  yes | apt install build-essential python3-dev python3-pip nodejs npm
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  apt-get update && apt-get install yarn

elif [[ "$OSTYPE" == "darwin"* ]]; then
  yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew update && brew upgrade
  brew install --with-default-names gnu-sed
  brew install python node yarn

fi

npm install -g @angular/cli

pip3 install --upgrade setuptools
cd h2o/backend
pip3 install -r requirements.txt
npm install orbit-db ipfs
cd ../frontend
yarn install --pure-lockfile

echo "
 _  _ ___ ___    ___ _  _ ___ _____ _   _    _    ___ ___
| || |_  ) _ \  |_ _| \| / __|_   _/_\ | |  | |  | __|   \\
| __ |/ / (_) |  | || .\` \__ \ | |/ _ \| |__| |__| _|| |) |
|_||_/___\___/  |___|_|\_|___/ |_/_/ \_\____|____|___|___/

"
