#!/bin/bash

if [ "$1" == kovan ]; then
  name=kovan
else
  name=docker-compose
fi

if [ "$(docker ps -aq -f name=ocean_keeper-contracts_1)" ]; then
  firstrun=0
else
  firstrun=1
fi

docker-compose -f ./ocean/$name.yml --project-name=ocean up &>/dev/null &

# Wait for Ocean to download and launch, note tendermint boots last.
# Add an extra 30 seconds for contract compilation on first time run.
if [ $firstrun == 1 ]; then
  echo "Compiling contracts..."
  while ! [ "$(docker ps -q -f name=ocean_keeper-contracts_1)" ];
  do
    echo "."
    sleep 5
  done
  echo "Booting Ocean Protocol..."
  sleep 30
fi

# Rebooting existing containers takes less time than starting frontend.

cd h2o/frontend
yarn start --ssl &
cd ../backend
chmod +x docker_run
echo "====================
      __ __
     / // /
    / _  /__
   /_//_/_  |
       / __/____
      /____/ __ \\
          / /_/ /
          \____/

====================
     Running at
https://0.0.0.0:4200
====================

"
./docker_run
