#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  export HOST_OS=linux
elif [[ "$OSTYPE" == "darwin"* ]]; then
  export HOST_OS=macos
else
  echo "Unsupported operating system. H2O runs on Linux and MacOS.
  If you think this is an error, force run with docker-compose up.
  There be dragons."
fi

red="\033[0;31m"
endcolor="\033[0m"
echo -e "
$red
     ____  __  __________   ___________
    / __ \/ / / /_  __/ /  /  _/ __/ _ \\
   / /_/ / /_/ / / / / /___/ // _// , _/
  _\____/\____/_/_/_/____/___/___/_/|_|___
 | | / / __/ |/ /_  __/ / / / _ \/ __/ __/
 | |/ / _//    / / / / /_/ / , _/ _/_\ \\
 |___/___/_/|_/ /_/  \____/_/|_/___/___/

$endcolor
"
docker-compose up

## --log-level ERROR e.g. for quiet build script
