version: '2.1'

# Run: docker-compose --project-name=ocean up

services:
  mongodb:
    image: mongo:3.6
    ports:
    - "27017:27017"
    command: mongod
    networks:
    - backend

  keeper-contracts:
    image: oceanprotocol/keeper-contracts:v0.3.19
    ports:
    - 8545:8545
    networks:
    - backend
    environment:
      LOCAL_CONTRACTS: "true"
      DEPLOY_CONTRACTS: "true"
      DATABASE_PATH: "/ganache-db"
      REUSE_DATABASE: "false"
      NETWORK_NAME: "ganache"
    volumes:
    - artifacts:/keeper-contracts/artifacts/

  aquarius:
    image: oceanprotocol/aquarius:develop

    ports:
    - 5000:5000
    networks:
    - backend
    depends_on:
    - keeper-contracts
    environment:
      KEEPER_URL: http://keeper-contracts:8545
      DB_HOSTNAME: mongodb
      LOCAL_CONTRACTS: 'true'
    volumes:
    - artifacts:/usr/local/keeper-contracts/:ro

networks:
  backend:

volumes:
  artifacts:
