#!/bin/bash

# START OCEAN FOR DEV MODE (NON-CONTAINERISED)

if [ "$1" == kovan ]; then
  name=kovan
else
  name=docker-compose
fi
screen -AdmS ocean bash -c 'docker-compose -f ./'$name'.yml up'
screen -r ocean
