#!/bin/bash

boldgreen="\033[1;32m"
boldred="\033[1;31m"
endcolor="\033[0m"

address=`cat address` || {
  echo -e "${boldred}Error: you need to run get_publisher before this script.$endcolor";
  exit 1;
}

echo -e "${boldgreen}Deploying a new set of Keeper contracts to Kovan...$endcolor"

if [ ! -d keeper-contracts ]; then
  git clone https://github.com/oceanprotocol/keeper-contracts.git || {
    echo -e "${boldred}Git clone failed. Try again or manually download the keeper contracts:
https://github.com/oceanprotocol/keeper-contracts
Place the keeper-contracts directory in this folder and run this script again.$endcolor"
    exit 1;
  }
fi

cp pass keeper-contracts/pass

cd keeper-contracts

if [ "$1" == latest ]; then
  git checkout -f develop;
elif [ "$1" == plankton ]; then
  git checkout -f 569d265;
else
  git checkout -f 415d9c0;
fi

cp ../truffle.js truffle.js

npm i

ganache-cli --version || npm install -g ganache-cli || { 
  echo -e "${boldred}NPM permissions error.
Install ganache-cli globally and run this script again.
If you have permissions errors, try:
${boldgreen}sudo chown -R $(whoami) ~/.npm
sudo chown -R $(whoami) ~/.npm-global
npm install -g ganache-cli
${boldred}If the ganache-cli command is not found, modify your PATH:
${boldgreen}PATH=\$PATH:~/.npm-global/bin$endcolor";
  exit 1;
}


# Migrate to Kovan
etherscan="https://kovan.etherscan.io/address/${address}"
if npm run migrate:kovan; then
  echo -e "${boldgreen}Deployment complete. Your contracts:
$etherscan$endcolor";
else
  echo -e "${boldred}Deployment failed, see logs above. For any successful contracts, see:
$etherscan$endcolor";
fi


# Copy new contracts to Squid's reference location
artifactspath="../../backend/artifacts"
rm -rf $artifactspath
cp -r artifacts $artifactspath


# Write to config_local.ini
pass=`cat pass` || {
  echo -e "${boldred}Error: can't read password file.$endcolor";
  exit 1;
}
cd ../../backend
if [ ! -f config_local.ini ]; then
  cp config.ini config_local.ini;
fi

sed -i -e "/parity.address =/ s/= .*/= $address/" config_local.ini
sed -i -e "/parity.password =/ s/= .*/= $pass/" config_local.ini
sed -i -e "/parity.address1 =/ s/= .*/= $address/" config_local.ini
sed -i -e "/parity.password1 =/ s/= .*/= $pass/" config_local.ini
rm config_local.ini-e


# Update frontend to display link to Kovan contracts
cd ../frontend/src/app/pages/home

sed -i -e "/publisher: string =/ s/= .*/= \"$address\"/" types.ts
rm types.ts-e

