#!/bin/bash

boldred="\033[1;31m"
endcolor="\033[0m"

address=`cat address` || {
  echo -e "${boldred}Error: Run get_publisher and deploy_contracts before this script.$endcolor";
  exit 1;
}
cd keeper-contracts
pass=`cat pass` || {
  echo -e "${boldred}Error: Run deploy_contracts before this script.$endcolor";
  exit 1;
}
parity account import ./keystore.json --chain kovan --password=./pass

parity --chain=kovan --jsonrpc-apis web3,eth,net,parity,traces,rpc,personal --jsonrpc-cors http://localhost:8545 --unlock=$address --password=./pass &
